// Lightweight country/city data for dropdowns.
// We can expand this over time.

export const COUNTRIES = [
  { code: "TR", name: "Turkey" },
  { code: "US", name: "United States" },
  { code: "DE", name: "Germany" },
  { code: "GB", name: "United Kingdom" },
  { code: "AE", name: "United Arab Emirates" },
];

export const CITIES_BY_COUNTRY = {
  TR: [
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Aksaray",
    "Amasya",
    "Ankara",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bartın",
    "Batman",
    "Bayburt",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Düzce",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Hatay",
    "Iğdır",
    "Isparta",
    "İstanbul",
    "İzmir",
    "Kahramanmaraş",
    "Karabük",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kilis",
    "Kırıkkale",
    "Kırklareli",
    "Kırşehir",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mersin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Sakarya",
    "Samsun",
    "Şanlıurfa",
    "Siirt",
    "Sinop",
    "Şırnak",
    "Sivas",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Uşak",
    "Van",
    "Yalova",
    "Yozgat",
    "Zonguldak",
  ],
  US: ["New York", "Los Angeles", "Chicago", "Miami", "San Francisco"],
  DE: ["Berlin", "Munich", "Hamburg", "Cologne", "Frankfurt"],
  GB: ["London", "Manchester", "Birmingham", "Leeds", "Glasgow"],
  AE: ["Dubai", "Abu Dhabi", "Sharjah"],
};

// Country-name keyed overrides for the web UI (the external dataset returns country names, not codes).
// Use this to keep dropdowns fast + consistent (avoid thousands of cities for some countries).
export const CITY_OVERRIDES_BY_COUNTRY_NAME = {
  // Germany override updated (latest user list)
  Germany: [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dortmund",
    "Essen",
    "Bremen",
    "Dresden",
    "Hanover",
    "Nuremberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Münster",
    "Karlsruhe",
    "Mannheim",
    "Augsburg",
    "Wiesbaden",
    "Gelsenkirchen",
    "Mönchengladbach",
    "Braunschweig",
    "Chemnitz",
    "Kiel",
    "Aachen",
    "Halle",
    "Magdeburg",
    "Freiburg",
    "Krefeld",
    "Mainz",
    "Lübeck",
    "Erfurt",
    "Oberhausen",
    "Rostock",
    "Kassel",
    "Hagen",
    "Saarbrücken",
    "Hamm",
    "Potsdam",
    "Ludwigshafen",
    "Oldenburg",
    "Leverkusen",
    "Osnabrück",
    "Solingen",
    "Heidelberg",
  ],

  // User-provided overrides (Dec 2025)
  "United Arab Emirates": [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Al Ain",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Umm Al Quwain",
    "Khor Fakkan",
    "Kalba",
    "Dibba Al-Fujairah",
    "Madinat Zayed",
    "Ruwais",
    "Liwa Oasis",
    "Dhaid",
    "Ghayathi",
    "Ar-Rams",
    "Dibba Al-Hisn",
    "Hatta",
    "Al Jazirah Al Hamra",
  ],

  // Accept common shorthand in case the UI ever uses it.
  UAE: [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Al Ain",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Umm Al Quwain",
    "Khor Fakkan",
    "Kalba",
    "Dibba Al-Fujairah",
    "Madinat Zayed",
    "Ruwais",
    "Liwa Oasis",
    "Dhaid",
    "Ghayathi",
    "Ar-Rams",
    "Dibba Al-Hisn",
    "Hatta",
    "Al Jazirah Al Hamra",
  ],

  Italy: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Genoa",
    "Bologna",
    "Florence",
    "Bari",
    "Catania",
    "Venice",
    "Verona",
    "Messina",
    "Padua",
    "Trieste",
    "Brescia",
    "Taranto",
    "Prato",
    "Parma",
    "Modena",
    "Reggio Calabria",
    "Reggio Emilia",
    "Perugia",
    "Ravenna",
    "Livorno",
    "Cagliari",
    "Foggia",
    "Rimini",
    "Salerno",
    "Ferrara",
    "Sassari",
    "Latina",
    "Giugliano in Campania",
    "Monza",
    "Syracuse",
    "Bergamo",
    "Pescara",
    "Trento",
    "Forlì",
    "Vicenza",
    "Terni",
    "Bolzano",
    "Novara",
    "Piacenza",
    "Ancona",
    "Andria",
    "Arezzo",
    "Udine",
    "Cesena",
    "Lecce",
  ],

  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Malaga",
    "Murcia",
    "Palma de Mallorca",
    "Las Palmas de Gran Canaria",
    "Bilbao",
    "Alicante",
    "Cordoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "L'Hospitalet de Llobregat",
    "Vitoria-Gasteiz",
    "A Coruña",
    "Elche",
    "Granada",
    "Terrassa",
    "Badalona",
    "Oviedo",
    "Cartagena",
    "Sabadell",
    "Jerez de la Frontera",
    "Móstoles",
    "Santa Cruz de Tenerife",
    "Pamplona",
    "Almería",
    "Alcalá de Henares",
    "Fuenlabrada",
    "Leganés",
    "San Sebastián",
    "Getafe",
    "Burgos",
    "Albacete",
    "Castellón de la Plana",
    "Santander",
    "Alcorcón",
    "San Cristóbal de La Laguna",
    "Logroño",
    "Badajoz",
    "Marbella",
    "Salamanca",
    "Huelva",
    "Lleida",
    "Tarragona",
    "Dos Hermanas",
    "Parla",
  ],

  Greece: [
    "Athens",
    "Thessaloniki",
    "Patras",
    "Piraeus",
    "Heraklion",
    "Larissa",
    "Peristeri",
    "Acharnes",
    "Kallithea",
    "Kalamaria",
    "Glyfada",
    "Nikaia",
    "Volos",
    "Ilion",
    "Evosmos",
    "Chalandri",
    "Ilioupoli",
    "Keratsini",
    "Nea Smyrni",
    "Marousi",
    "Agios Dimitrios",
    "Zografou",
    "Egaleo",
    "Ioannina",
    "Palaio Faliro",
    "Nea Ionia",
    "Chalcis (Chalkida)",
    "Agia Paraskevi",
    "Trikala",
    "Korydallos",
    "Petroupoli",
    "Alexandroupoli",
    "Serres",
    "Katerini",
    "Vyronas",
    "Kalamata",
    "Xanthi",
    "Galatsi",
    "Rhodes",
    "Chania",
    "Komotini",
    "Kavala",
    "Agrinio",
    "Lamia",
    "Drama",
    "Veria",
    "Kozani",
    "Karditsa",
    "Rethymno",
    "Corinth",
  ],

  // France (user-provided)
  France: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Montpellier",
    "Strasbourg",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Toulon",
    "Saint-Étienne",
    "Le Havre",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Villeurbanne",
    "Aix-en-Provence",
    "Le Mans",
    "Clermont-Ferrand",
    "Brest",
    "Tours",
    "Amiens",
    "Limoges",
    "Annecy",
    "Perpignan",
    "Boulogne-Billancourt",
    "Metz",
    "Besançon",
    "Orléans",
    "Saint-Denis",
    "Argenteuil",
    "Rouen",
    "Mulhouse",
    "Montreuil",
    "Caen",
    "Nancy",
    "Saint-Paul",
    "Roubaix",
    "Tourcoing",
    "Nanterre",
    "Vitry-sur-Seine",
    "Créteil",
    "Avignon",
    "Poitiers",
    "Courbevoie",
    "Versailles",
  ],

  // United States (user-provided)
  "United States": [
    "New York City",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington, D.C.",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Omaha",
    "Colorado Springs",
    "Raleigh",
    "Long Beach",
    "Virginia Beach",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Bakersfield",
    "Wichita",
    "Arlington",
  ],

  // Accept common shorthand in case the UI ever uses it.
  USA: [
    "New York City",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington, D.C.",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Omaha",
    "Colorado Springs",
    "Raleigh",
    "Long Beach",
    "Virginia Beach",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Bakersfield",
    "Wichita",
    "Arlington",
  ],

  // Turkey (user-provided)
  Turkey: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Bursa",
    "Antalya",
    "Konya",
    "Adana",
    "Sanliurfa",
    "Gaziantep",
    "Kocaeli",
    "Mersin",
    "Diyarbakir",
    "Hatay",
    "Manisa",
    "Kayseri",
    "Samsun",
    "Balikesir",
    "Kahramanmaras",
    "Van",
    "Aydin",
    "Tekirdag",
    "Sakarya",
    "Denizli",
    "Mugla",
    "Eskisehir",
    "Mardin",
    "Trabzon",
    "Malatya",
    "Ordu",
    "Erzurum",
    "Afyonkarahisar",
    "Sivas",
    "Adiyaman",
    "Batman",
    "Tokat",
    "Elazig",
    "Zonguldak",
    "Kutahya",
    "Osmaniye",
    "Canakkale",
    "Corum",
    "Sirnak",
    "Agri",
    "Giresun",
    "Isparta",
    "Aksaray",
    "Yozgat",
    "Edirne",
    "Mus",
    "Duzce",
    "Kastamonu",
    "Usak",
    "Kirklareli",
    "Nigde",
    "Bitlis",
    "Rize",
    "Amasya",
    "Siirt",
    "Bolu",
    "Nevsehir",
    "Yalova",
    "Bingol",
    "Kirikkale",
    "Hakkari",
    "Karaman",
    "Karabuk",
    "Burdur",
    "Erzincan",
    "Kirsehir",
    "Bilecik",
    "Sinop",
    "Igdir",
    "Bartin",
    "Cankiri",
    "Artvin",
    "Kilis",
    "Gumushane",
    "Ardahan",
    "Tunceli",
    "Bayburt",
  ],

  // Portugal (user-provided)
  Portugal: [
    "Lisbon",
    "Porto",
    "Vila Nova de Gaia",
    "Amadora",
    "Braga",
    "Funchal",
    "Coimbra",
    "Setúbal",
    "Agualva-Cacém",
    "Almada",
    "Queluz",
    "Guimarães",
    "Barreiro",
    "Aveiro",
    "Viseu",
    "Odivelas",
    "Matosinhos",
    "Rio Tinto",
    "Póvoa de Varzim",
    "Évora",
    "Maia",
    "Ermesinde",
    "Castelo Branco",
    "Faro",
    "Portimão",
    "Gondomar",
    "Cascais",
    "Santarém",
    "Figueira da Foz",
    "Beja",
    "Covilhã",
    "Espinho",
    "Guarda",
    "Caldas da Rainha",
    "Santo Tirso",
    "Marinha Grande",
    "Vila do Conde",
    "Loures",
    "Oliveira de Azeméis",
    "Canidelo",
    "Loulé",
    "Quarteira",
    "Angra do Heroísmo",
    "Sines",
    "Viana do Castelo",
    "Tomar",
    "Chaves",
    "Entroncamento",
    "Bragança",
    "Ponta Delgada",
  ],

  // Denmark (user-provided)
  Denmark: [
    "Copenhagen",
    "Aarhus",
    "Odense",
    "Aalborg",
    "Esbjerg",
    "Randers",
    "Kolding",
    "Horsens",
    "Vejle",
    "Roskilde",
    "Herning",
    "Hørsholm",
    "Helsingør",
    "Silkeborg",
    "Næstved",
    "Fredericia",
    "Viborg",
    "Køge",
    "Holstebro",
    "Taastrup",
    "Slagelse",
    "Hillerød",
    "Sønderborg",
    "Holbæk",
    "Svendborg",
    "Hjørring",
    "Frederikshavn",
    "Nørresundby",
    "Ringsted",
    "Ølstykke-Stenløse",
    "Skive",
    "Birkerød",
    "Farum",
    "Smørumnedre",
    "Skanderborg",
    "Nyborg",
    "Solrød Strand",
    "Lillerød",
    "Frederikssund",
    "Aabenraa",
    "Middelfart",
    "Hadsten",
    "Ikast",
    "Korsør",
    "Grenaa",
    "Varde",
    "Rønne",
    "Thisted",
    "Værløse",
    "Nakskov",
  ],

  // Belgium (user-provided)
  Belgium: [
    "Brussels",
    "Antwerp",
    "Ghent",
    "Charleroi",
    "Liège",
    "Bruges",
    "Namur",
    "Leuven",
    "Mons",
    "Aalst",
    "Mechelen",
    "La Louvière",
    "Hasselt",
    "Kortrijk",
    "Sint-Niklaas",
    "Ostend",
    "Tournai",
    "Genk",
    "Seraing",
    "Roeselare",
    "Mouscron",
    "Verviers",
    "Forest",
    "Woluwe-Saint-Lambert",
    "Jette",
    "Beveren",
    "Etterbeek",
    "Dendermonde",
    "Beringen",
    "Turnhout",
    "Dilbeek",
    "Heist-op-den-Berg",
    "Wavre",
    "Sint-Truiden",
    "Lokeren",
    "Vilvoorde",
    "Herstal",
    "Braine-l'Alleud",
    "Brasschaat",
    "Maasmechelen",
    "Molenbeek-Saint-Jean",
    "Ixelles",
    "Uccle",
    "Anderlecht",
    "Geel",
    "Halle",
    "Grimbergen",
    "Knokke-Heist",
    "Schoten",
    "Waregem",
  ],

  // Russia (user-provided)
  Russia: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Kazan",
    "Nizhny Novgorod",
    "Chelyabinsk",
    "Samara",
    "Omsk",
    "Rostov-on-Don",
    "Ufa",
    "Krasnoyarsk",
    "Voronezh",
    "Perm",
    "Volgograd",
    "Krasnodar",
    "Saratov",
    "Tyumen",
    "Tolyatti",
    "Barnaul",
    "Izhevsk",
    "Makhachkala",
    "Ulyanovsk",
    "Irkutsk",
    "Vladivostok",
    "Yaroslavl",
    "Kemerovo",
    "Khabarovsk",
    "Orenburg",
    "Novokuznetsk",
    "Ryazan",
    "Tomsk",
    "Astrakhan",
    "Penza",
    "Naberezhnye Chelny",
    "Lipetsk",
    "Kirov",
    "Cheboksary",
    "Tula",
    "Kaliningrad",
    "Balashikha",
    "Kursk",
    "Sevastopol",
    "Stavropol",
    "Ulan-Ude",
    "Tver",
    "Magnitogorsk",
    "Sochi",
    "Ivanovo",
    "Bryansk",
  ],

  // Sweden (user-provided)
  Sweden: [
    "Stockholm",
    "Gothenburg",
    "Malmö",
    "Uppsala",
    "Upplands Väsby and Sollentuna",
    "Västerås",
    "Örebro",
    "Linköping",
    "Helsingborg",
    "Jönköping",
    "Norrköping",
    "Lund",
    "Umeå",
    "Gävle",
    "Borås",
    "Södertälje",
    "Eskilstuna",
    "Halmstad",
    "Växjö",
    "Karlstad",
    "Täby",
    "Sundsvall",
    "Östersund",
    "Trollhättan",
    "Luleå",
    "Lidingö",
    "Boras",
    "Tumba",
    "Kristianstad",
    "Kalmar",
    "Falun",
    "Skövde",
    "Karlskrona",
    "Skellefteå",
    "Uddevalla",
    "Varberg",
    "Åkersberga",
    "Örnsköldsvik",
    "Landskrona",
    "Nyköping",
    "Motala",
    "Vallentuna",
    "Gunnebo",
    "Trelleborg",
    "Ängelholm",
    "Karlskoga",
    "Enköping",
    "Lerum",
    "Alingsås",
    "Sandviken",
  ],

  // Norway (user-provided)
  Norway: [
    "Oslo",
    "Bergen",
    "Stavanger",
    "Trondheim",
    "Drammen",
    "Fredrikstad",
    "Sandnes",
    "Kristiansand",
    "Sarpsborg",
    "Tønsberg",
    "Skien",
    "Ålesund",
    "Sandefjord",
    "Larvik",
    "Arendal",
    "Moss",
    "Porsgrunn",
    "Bodø",
    "Haugesund",
    "Tromsø",
    "Hamarkameratene (Hamar)",
    "Halden",
    "Sandvika",
    "Lillehammer",
    "Gjøvik",
    "Askøy",
    "Molde",
    "Kongsberg",
    "Horten",
    "Ski",
    "Mo i Rana",
    "Jessheim",
    "Kristiansund",
    "Hønefoss",
    "Narvik",
    "Alta",
    "Elverum",
    "Askim",
    "Leirvik",
    "Grimstad",
    "Steinkjer",
    "Kongsvinger",
    "Vennesla",
    "Mandal",
    "Stjørdalshalsen",
    "Egersund",
    "Førde",
    "Drøbak",
    "Harstad",
    "Brumunddal",
  ],
};

// ---- Country/city matching helpers (avoid "no match" bugs) ----

const COUNTRY_CODE_TO_NAME = COUNTRIES.reduce((acc, c) => {
  acc[String(c.code)] = String(c.name);
  return acc;
}, {});

function safeString(v) {
  if (v === null || v === undefined) return "";
  return String(v);
}

export function normalizeCountryKey(name) {
  const raw = safeString(name).trim();
  if (!raw) return "";

  // Remove diacritics to make matching tolerant (e.g. Türkiye/Turkiye, München/Munchen)
  const noDiacritics = raw.normalize("NFD").replace(/[\u0300-\u036f]/g, "");

  return noDiacritics
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .replace(/\s+/g, " ");
}

// Normalize common user/legacy variants to a canonical country name.
const COUNTRY_NAME_ALIASES = {
  uae: "United Arab Emirates",
  "u a e": "United Arab Emirates",
  "united arab emirates": "United Arab Emirates",
  emirates: "United Arab Emirates",

  usa: "United States",
  us: "United States",
  "u s": "United States",
  "united states": "United States",
  "united states of america": "United States",

  turkiye: "Turkey",
  "t u r k i y e": "Turkey",
  türkiye: "Turkey",
  turkey: "Turkey",

  "russian federation": "Russia",
  russia: "Russia",
};

export function resolveCanonicalCountryName(countryLike) {
  const raw = safeString(countryLike).trim();
  if (!raw) return "";

  // If it's a country code (TR/US/AE/etc) map it first.
  const upper = raw.toUpperCase();
  if (upper.length === 2 && COUNTRY_CODE_TO_NAME[upper]) {
    return COUNTRY_CODE_TO_NAME[upper];
  }

  const norm = normalizeCountryKey(raw);
  if (!norm) return raw;

  // Alias mapping.
  const aliased = COUNTRY_NAME_ALIASES[norm];
  if (aliased) return aliased;

  // If the override object already contains a key that matches (case/diacritics-insensitive), use it.
  const overrideKeys = Object.keys(CITY_OVERRIDES_BY_COUNTRY_NAME || {});
  for (const k of overrideKeys) {
    if (normalizeCountryKey(k) === norm) return k;
  }

  return raw;
}

export function getCityOverrideForCountry(countryLike) {
  const canonical = resolveCanonicalCountryName(countryLike);
  if (!canonical) return null;

  const direct = CITY_OVERRIDES_BY_COUNTRY_NAME?.[canonical];
  if (Array.isArray(direct) && direct.length > 0) return direct;

  // As a fallback, try normalized key lookup across override keys.
  const target = normalizeCountryKey(canonical);
  const keys = Object.keys(CITY_OVERRIDES_BY_COUNTRY_NAME || {});
  for (const k of keys) {
    if (normalizeCountryKey(k) === target) {
      const v = CITY_OVERRIDES_BY_COUNTRY_NAME?.[k];
      if (Array.isArray(v) && v.length > 0) return v;
    }
  }

  return null;
}

export function getCitiesForCountry(countryCode) {
  if (!countryCode) return [];
  const arr = CITIES_BY_COUNTRY[countryCode];
  return Array.isArray(arr) ? arr : [];
}
